apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: yoyo
  name: api
  namespace: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: 'vikrant1020/react:latest'
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 150m
      restartPolicy: Always
