---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - image: 'seasiainfotechdocker/nodekube:10'
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 150m
      restartPolicy: Always
